### PR TITLE
Added partner logos and links to partners web sites. Sliders will sli…

### PR DESCRIPTION
**Pull request by acengic**
…de images if all images are not visible.

### CODE REVIEW

**Comment by garnertb** [comment]
These changes look great!  Some suggestions: 

- [ ] Include the USFA partner logo. 
- [ ] Rename iaf.jpg to iaff.jpg
- [ ] Move inline styles (width='165px') into the css rules. 
- [ ] Remove old content-partners-* images.
- [ ] Remove comments from the style.css for the centering fix.
- [ ] Rebase these commits on top of the latest in master.

**Comment by garnertb** [comment]
Also, I added a section to the README (https://github.com/FireCARES/firecares#generating-css) that discusses how to make modifications to CSS rules from the LESS files.

**Comment by acengic** [comment]
I’ve pushed this changes so I can enter time for july. I need to fix “gather static” issue so I can test these changes and make corrections.
This is an exception to the rule.

**Comment by acengic** [comment]
These are all pretty obvious errors, except for image width (dimensions). 
They can be attributes (in HTML) or style in CSS, or both. So just to confirm you want always to keep image dimension as style in CSS not in HTML.

**Comment by garnertb** [comment]
I would prefer them as attributes in the HTML directive (width and
height).  They should not be specified in the style attribute of the HTML
directive.

On Mon, Aug 3, 2015 at 10:25 AM, acengic <notifications@github.com> wrote:

> These are all pretty obvious errors, except for image width (dimensions).
> They can be attributes (in HTML) or style in CSS, or both. So just to
> confirm you want always to keep image dimension as style in CSS not in HTML.
>
> On Aug 1, 2015, at 1:35 PM, Tyler Garner <notifications@github.com> wrote:
>
> > Also, I added a section to the README (
> https://github.com/FireCARES/firecares#generating-css) that discusses how
> to make modifications to CSS rules from the LESS files.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FireCARES/firecares/pull/6#issuecomment-127260332>.
>



-- 
-Tyler Garner

**Comment by acengic** [comment]
Tyler,
I was testing “dial number position” on Safari and it looks like dial (hand)  is shown in different way - CSS issue.
I work on Chrome. Can you check link bellow in Safari?
https://ec2-52-5-181-172.compute-1.amazonaws.com/departments/88539/miami-dade-fire-rescue-department

**Comment by garnertb** [comment]
Confirmed, I created a new issue for it: https://github.com/FireCARES/firecares/issues/8

**Comment by acengic** [comment]
Can you confirm that this on looks OK in Safari, other than number alignment.
https://ec2-52-5-181-172.compute-1.amazonaws.com/departments/91012/miami-dade-fire-rescue-department

**Comment by garnertb** [comment]
Confirmed.

**Comment by acengic** [comment]
Partners logos, fixed errors, use width HTML attribute, renamed iaf.png to iaff.png

**Comment by garnertb** [comment]
I cherry picked the pertinent commits from this.

**Pull request closed without merging**
