### PR TITLE
3.E Service Area

### PR DESCRIPTION
**Pull request by joliveros**
WIP

### CODE REVIEW

**Comment by saltaverde** [comment]
Things are working now. Here is a summary of the changes:
- `service_area_0_4`, `service_area_4_6`, and `service_area_6_8` fields added to the `FireStation` model
- update task added to fetch station service areas from mapbox api
- department service area update task uses mapbox api
- endpoint added to the firecares API: `/api/v1/firestation/{id}/service-area` which fetches service area geometries from mapbox if not found in the database
- front end looks for service area data in the `FireStation` resource, if not found it calls the API
- update task for the department does not run if only the station service areas are being updated

I have not been successful in getting the test suite to run. Not sure how we want to handle that @joliveros @garnertb

**Comment by joliveros** [comment]
Hi @saltaverde ,
I was able to get the tests running within
 the firecares container after adding the migrations above. Give it a try and let me know if you have any more trouble.

how do you feel about adding a few tests to the tasks and the new service area endpoint?

**Comment by saltaverde** [comment]
@joliveros I'll give that a try, thanks. Definitely tests should be added, I just wasn't sure how to proceed since the tests weren't running.

**Review by joliveros — COMMENTED** [review]
Thanks for adding the test for the service areas end-point!

How do you feel about adding some tests for the `run_update_department_task` as well as the update service area task?

**Comment by saltaverde** [comment]
@joliveros I feel great about it! ha! also @garnertb wants the other code that relies upon `gis.iaff.org` to be changed.

**Comment by saltaverde** [comment]
@joliveros I added a test for `update_station_service_area`, did you want a specific test for `update_parcel_department_hazard_level`? I believe that is tested implicitly by `test_calculate_service_area_metrics`

**Comment by joliveros** [comment]
> @joliveros I added a test for `update_station_service_area`, did you want a specific test for `update_parcel_department_hazard_level`? I believe that is tested implicitly by `test_calculate_service_area_metrics`

looks good @saltaverde! If it's tested implicitly then I think we can pass on testing `update_parcel_department_hazard_level` for now. I'll try to test locally and see if I can see anything else that may be worth testing. Unless you have any suggestions?

**Pull request merged**
